#!/usr/bin/env python3
'''
This node is meant to detect hands of the user it is following using media pipe
If hands are detected, publish to a topic that the main node subscribes too. Something
along the lines of a string or a number. It would stop the robot from following the person 
and then make the sawyer arm move. After it complete this motion, the sawyer arm should
publish to the same topic to make the ridgeback move again.
1) detect hands, if so publish to [topic1]
2) manipulation subscribes to [topic1] and stops the ridgeback from following then
stars the arm movement.
3) once arm is done moving, publish to [topic1] to have the robot start moving again.
4) rinse and repeat
'''

def main(): #The main function.
    a = 0
    
    


